// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.27.1
// source: feast/core/SparkOverride.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SparkOverride struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Override CPU requested for driver
	DriverCpu int32 `protobuf:"varint,1,opt,name=driver_cpu,json=driverCpu,proto3" json:"driver_cpu,omitempty"`
	// Override memory requested for driver
	DriverMemory string `protobuf:"bytes,2,opt,name=driver_memory,json=driverMemory,proto3" json:"driver_memory,omitempty"`
	// Override CPU requested for executor
	ExecutorCpu int32 `protobuf:"varint,3,opt,name=executor_cpu,json=executorCpu,proto3" json:"executor_cpu,omitempty"`
	// Override memory requested for executor
	ExecutorMemory string `protobuf:"bytes,4,opt,name=executor_memory,json=executorMemory,proto3" json:"executor_memory,omitempty"`
}

func (x *SparkOverride) Reset() {
	*x = SparkOverride{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feast_core_SparkOverride_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SparkOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparkOverride) ProtoMessage() {}

func (x *SparkOverride) ProtoReflect() protoreflect.Message {
	mi := &file_feast_core_SparkOverride_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparkOverride.ProtoReflect.Descriptor instead.
func (*SparkOverride) Descriptor() ([]byte, []int) {
	return file_feast_core_SparkOverride_proto_rawDescGZIP(), []int{0}
}

func (x *SparkOverride) GetDriverCpu() int32 {
	if x != nil {
		return x.DriverCpu
	}
	return 0
}

func (x *SparkOverride) GetDriverMemory() string {
	if x != nil {
		return x.DriverMemory
	}
	return ""
}

func (x *SparkOverride) GetExecutorCpu() int32 {
	if x != nil {
		return x.ExecutorCpu
	}
	return 0
}

func (x *SparkOverride) GetExecutorMemory() string {
	if x != nil {
		return x.ExecutorMemory
	}
	return ""
}

var File_feast_core_SparkOverride_proto protoreflect.FileDescriptor

var file_feast_core_SparkOverride_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x53, 0x70, 0x61,
	0x72, 0x6b, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x9f, 0x01, 0x0a,
	0x0d, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x43, 0x70, 0x75, 0x12, 0x23, 0x0a,
	0x0d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x5f, 0x63,
	0x70, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x43, 0x70, 0x75, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x42, 0x7e,
	0x0a, 0x1e, 0x64, 0x65, 0x76, 0x2e, 0x63, 0x61, 0x72, 0x61, 0x6d, 0x6c, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x42, 0x12, 0x53, 0x70, 0x61, 0x72, 0x6b, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x72, 0x61, 0x6d, 0x6c, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x63, 0x61, 0x72, 0x61,
	0x6d, 0x6c, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x61, 0x6d, 0x6c, 0x2d,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feast_core_SparkOverride_proto_rawDescOnce sync.Once
	file_feast_core_SparkOverride_proto_rawDescData = file_feast_core_SparkOverride_proto_rawDesc
)

func file_feast_core_SparkOverride_proto_rawDescGZIP() []byte {
	file_feast_core_SparkOverride_proto_rawDescOnce.Do(func() {
		file_feast_core_SparkOverride_proto_rawDescData = protoimpl.X.CompressGZIP(file_feast_core_SparkOverride_proto_rawDescData)
	})
	return file_feast_core_SparkOverride_proto_rawDescData
}

var file_feast_core_SparkOverride_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feast_core_SparkOverride_proto_goTypes = []interface{}{
	(*SparkOverride)(nil), // 0: feast.core.SparkOverride
}
var file_feast_core_SparkOverride_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feast_core_SparkOverride_proto_init() }
func file_feast_core_SparkOverride_proto_init() {
	if File_feast_core_SparkOverride_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_feast_core_SparkOverride_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SparkOverride); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feast_core_SparkOverride_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feast_core_SparkOverride_proto_goTypes,
		DependencyIndexes: file_feast_core_SparkOverride_proto_depIdxs,
		MessageInfos:      file_feast_core_SparkOverride_proto_msgTypes,
	}.Build()
	File_feast_core_SparkOverride_proto = out.File
	file_feast_core_SparkOverride_proto_rawDesc = nil
	file_feast_core_SparkOverride_proto_goTypes = nil
	file_feast_core_SparkOverride_proto_depIdxs = nil
}
