# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feast/core/Entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feast.types import Value_pb2 as feast_dot_types_dot_Value__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x65\x61st/core/Entity.proto\x12\nfeast.core\x1a\x17\x66\x65\x61st/types/Value.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"`\n\x06\x45ntity\x12*\n\x04spec\x18\x01 \x01(\x0b\x32\x16.feast.core.EntitySpecR\x04spec\x12*\n\x04meta\x18\x02 \x01(\x0b\x32\x16.feast.core.EntityMetaR\x04meta\"\xf5\x01\n\nEntitySpec\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12:\n\nvalue_type\x18\x02 \x01(\x0e\x32\x1b.feast.types.ValueType.EnumR\tvalueType\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12:\n\x06labels\x18\x08 \x03(\x0b\x32\".feast.core.EntitySpec.LabelsEntryR\x06labels\x1a\x39\n\x0bLabelsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xa7\x01\n\nEntityMeta\x12G\n\x11\x63reated_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x10\x63reatedTimestamp\x12P\n\x16last_updated_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x14lastUpdatedTimestampBw\n\x1e\x64\x65v.caraml.store.protobuf.coreB\x0b\x45ntityProtoZHgithub.com/caraml-dev/caraml-store/caraml-store-sdk/go/protos/feast/coreb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feast.core.Entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036dev.caraml.store.protobuf.coreB\013EntityProtoZHgithub.com/caraml-dev/caraml-store/caraml-store-sdk/go/protos/feast/core'
  _ENTITYSPEC_LABELSENTRY._options = None
  _ENTITYSPEC_LABELSENTRY._serialized_options = b'8\001'
  _ENTITY._serialized_start=97
  _ENTITY._serialized_end=193
  _ENTITYSPEC._serialized_start=196
  _ENTITYSPEC._serialized_end=441
  _ENTITYSPEC_LABELSENTRY._serialized_start=384
  _ENTITYSPEC_LABELSENTRY._serialized_end=441
  _ENTITYMETA._serialized_start=444
  _ENTITYMETA._serialized_end=611
# @@protoc_insertion_point(module_scope)
