name: CaraML Store Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # This is required because our versioning strategy depends on parent tags
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build gRPC service images
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
        with:
          arguments: jib
      - name: Build Spark application image
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
        with:
          arguments: caraml-store-spark:docker
      - name: Push Spark application image
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}
        with:
          arguments: caraml-store-spark:dockerPush
